version: '3.4'

services:
  parking.webapi:
    image: ${DOCKER_REGISTRY}parkingwebapi
    build:
      context: .
      dockerfile: src/Parking.WebAPI/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "abc,12345678"
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - '11433:1433'

volumes:
  mssql_data: